server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

# Lavalink core configuration
lavalink:
  plugins:
    # Load the required Lavalink plugins
    - dependency: 'dev.lavalink.youtube:youtube-plugin:1.15.0'
    - dependency: 'com.github.topi314.lavasrc:lavasrc-plugin:4.5.0'

  server:
    password: 'youshallnotpass'

    # Disable built-in YouTube source since the plugin handles it
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false

    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

    nonAllocatingFrameBuffer: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

    timeouts:
      connectTimeoutMs: 3000
      connectionRequestTimeoutMs: 3000
      socketTimeoutMs: 3000

# Plugin configurations
plugins:
  lavasrc:
    sources:
      spotify: true
      applemusic: true
      deezer: true
      youtube: true

    # Credentials (replace with your own)
    spotify:
      clientId: your-client-id
      clientSecret: your-client-secret
      spDc: 0123456789
    deezer:
      masterDecryptionKey: your-master-decryption-key
      arl: '0123456789'
    tidal:
      countryCode: 'DE'
      searchLimit: 6
      token: 0123456789

# Metrics configuration
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

# Sentry error tracking
sentry:
  dsn: ''
  environment: ''

# Logging configuration
logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
