services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.1.1-alpine
    container_name: lavalink
    restart: unless-stopped
    user: '1000:1000'
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins
    ports:
      - '2333:2333'
    networks:
      - lavalink

networks:
  lavalink:
    name: lavalink
    driver: bridge
